Exception in thread Thread-1 (run_reciever):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-1 (run_reciever):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    self.run()
Exception in thread Thread-1 (run_reciever):
Traceback (most recent call last):
  File "/home/windware/Desktop/Windware - Website/receive_data_raspberry.py", line 29, in run_reciever
  File "/usr/lib/python3.11/threading.py", line 975, in run
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/home/windware/Desktop/Windware - Website/receive_data_raspberry.py", line 29, in run_reciever
    line = ser.readline().decode('utf-8').strip()  # Læser én linje og dekoder den til tekst
           ^^^^^^^^^^^^^^
  File "/home/windware/Desktop/Windware - Website/venv/lib/python3.11/site-packages/serial/serialposix.py", line 595, in read
  File "/usr/lib/python3.11/threading.py", line 975, in run
    raise SerialException(
    line = ser.readline().decode('utf-8').strip()  # Læser én linje og dekoder den til tekst
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
           ^^^^^^^^^^^^^^
  File "/home/windware/Desktop/Windware - Website/venv/lib/python3.11/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
    self._target(*self._args, **self._kwargs)
raw line IND_DI:100,WIND_SPEED:0,POWER:0,WIND_DIR_CHANGE:0
Exception in thread Thread-1 (run_reciever):
  File "/home/windware/Desktop/Windware - Website/receive_data_raspberry.py", line 29, in run_reciever
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    line = ser.readline().decode('utf-8').strip()  # Læser én linje og dekoder den til tekst
           ^^^^^^^^^^^^^^
  File "/home/windware/Desktop/Windware - Website/venv/lib/python3.11/site-packages/serial/serialposix.py", line 595, in read
    self.run()
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/windware/Desktop/Windware - Website/receive_data_raspberry.py", line 33, in run_reciever
    print(f"Vindretning: {data['WIND_DIR']} grader, "
                          ~~~~^^^^^^^^^^^^
KeyError: 'WIND_DIR'


and

Starter modtagelse af data...
Starter modtagelse af data...
Starter modtagelse af data...
Starter modtagelse af data...
1500.0
1500.0
1500.0
1500.0
[Serial Error] device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[Serial Error] device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[Serial Error] device reports readiness to read but returned no data (device disconnected or multiple access on port?)
raw line N_:0SE:OWE:0,WIND_DIR_CHANGE:0
vindretning: unknown grader, Vindhastighed: unknown, Effekt unknown, Retningsændring 0
1500.0
1500.0
1500.0
1500.0
[Serial Error] device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[Serial Error] device reports readiness to read but returned no data (device disconnected or multiple access on port?)
raw line R0NSD,OW:W__AG:0
vindretning: unknown grader, Vindhastighed: unknown, Effekt unknown, Retningsændring unknown
raw line NI1WID_PEE:0PER0,INDDIRCHNE
vindretning: unknown grader, Vindhastighed: unknown, Effekt unknown, Retningsændring unknown
1500.0
1500.0
1500.0
1500.0
[Serial Error] device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[Serial Error] device reports readiness to read but returned no data (device disconnected or multiple access on port?)
raw line N:0ND_PEE:,OWER:0WIN_DIRCAGE:6
vindretning: unknown grader, Vindhastighed: unknown, Effekt unknown, Retningsændring unknown
raw line WDR80,SD91P,D_HN
vindretning: unknown grader, Vindhastighed: unknown, Effekt unknown, Retningsændring unknown
^C[2025-05-12 18:14:04 +0200] [3299] [INFO] Handling signal: int
[2025-05-12 18:14:04 +0200] [3303] [INFO] Worker exiting (pid: 3303)
[2025-05-12 18:14:04 +0200] [3301] [INFO] Worker exiting (pid: 3301)
[2025-05-12 18:14:07 +0200] [3299] [INFO] Shutting down: Master
